# Generated by Django 3.2.5 on 2023-06-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_chips_handicap_race_results_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='first_name', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='surname', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='swims_in',
            field=models.ManyToManyField(blank=True, related_name='swims_in', to='timer.Race'),
        ),
    ]
