# Generated by Django 3.2.5 on 2023-06-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_auto_20230626_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
