# Generated by Django 3.2.5 on 2023-06-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0006_rename_user_profile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
